// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT-5NuW_dS-xIBSzCACAAiwUiKxlY4Ehc',
    appId: '1:786851699467:android:f6d129e8fe9662c8aa600e',
    messagingSenderId: '786851699467',
    projectId: 'welness-6b05a',
    storageBucket: 'welness-6b05a.appspot.com',

  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPnkOl6oNbLN_g1B-Tl4_qxQAVBSu8VDg',
    appId: '1:786851699467:web:928f80a9f7f792a0aa600e',
    messagingSenderId: '786851699467',
    projectId: 'welness-6b05a',
    authDomain: 'welness-6b05a.firebaseapp.com',
    storageBucket: 'welness-6b05a.firebasestorage.app',
  );

}